#!/usr/bin/env python3
"""Automated tests for harness-bridge (server.py).

The MCP server is started for real over stdio (the same way OpenCode / Claude Code start
it) but pointed at *fake* `agy` and `claude` binaries, so the suite is hermetic and
consumes no quota. Pure helpers are imported and unit-tested directly.

Run:   python test_bridge.py            (stdlib unittest)
  or:  python -m pytest -q test_bridge.py
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SERVER = HERE / "server.py"
sys.path.insert(0, str(HERE))

import server as bridge  # noqa: E402

from mcp import ClientSession, StdioServerParameters  # noqa: E402
from mcp.client.stdio import stdio_client  # noqa: E402

logging.getLogger().setLevel(logging.WARNING)  # keep SDK/asyncio chatter out of the test output
logging.getLogger("asyncio").setLevel(logging.ERROR)  # IsolatedAsyncioTestCase runs the loop in debug mode

AGY = bridge.HARNESSES["antigravity"]
CLAUDE = bridge.HARNESSES["claude_code"]

FAKE_HARNESS = r'''#!/usr/bin/env python3
"""Fake harness binary for test_bridge.py: acts as `agy` or `claude` depending on its file name."""
import json, os, signal, subprocess, sys

name = os.path.basename(sys.argv[0])
args = sys.argv[1:]
is_claude = name == "claude"


def out(text):
    sys.stdout.write(text)
    sys.stdout.flush()


if args[:1] == ["--version"]:
    out("9.9.9-fake (Claude Code)\n" if is_claude else "9.9.9-fake\n")
    sys.exit(0)
if not is_claude and args[:1] == ["models"]:
    if os.environ.get("FAKE_AUTH_FAIL"):
        sys.stderr.write("Error: not authenticated. Run 'agy' interactively to log in.\n")
        sys.exit(1)
    out("Fetching available models...\nfake-model-high\tFake Model (High)\nfake-model-low\tFake Model (Low)\n")
    sys.exit(0)
if is_claude and args[:2] == ["auth", "status"]:
    out(json.dumps({
        "loggedIn": not os.environ.get("FAKE_AUTH_FAIL"), "authMethod": "claude.ai", "apiProvider": "firstParty",
        "subscriptionType": "max", "email": "secret-email@example.com", "orgId": "secret-org",
    }) + "\n")
    sys.exit(0)

VALUE_OPTS = {"--output-format", "--print-timeout", "--model", "--conversation", "--resume", "--effort",
              "--add-dir", "--max-turns", "--mode", "--permission-mode"}
prompt = None
source = "stdin"
resume = None
i = 0
while i < len(args):
    a = args[i]
    if a in ("-p", "--print", "--prompt"):
        if is_claude:          # boolean flag; the prompt is positional
            i += 1
            continue
        prompt, source = args[i + 1], "arg"
        i += 2
        continue
    if a in ("--conversation", "--resume"):
        resume = args[i + 1]
        i += 2
        continue
    if a in VALUE_OPTS:
        i += 2
        continue
    if a.startswith("-"):
        i += 1
        continue
    if is_claude and prompt is None:
        prompt, source = a, "arg"
    i += 1
if prompt is None:
    prompt = sys.stdin.read()

shown_args = ["<PROMPT>" if a == prompt else a for a in args]
lines = [
    "FAKE_ARGS: " + " ".join(shown_args),
    "FAKE_PROMPT_SOURCE: " + source,
    "FAKE_PROMPT_LEN: " + str(len(prompt)),
    "FAKE_ENV_MARKER: " + os.environ.get("FAKE_ENV_MARKER", "unset"),
    "FAKE_CWD: " + os.getcwd(),
    "FAKE_DEPTH: " + os.environ.get("BRIDGE_DEPTH", "unset"),
    "FAKE_CLAUDECODE: " + os.environ.get("CLAUDECODE", "unset"),
    "FAKE_RESUME: " + (resume or "none"),
]
text = "\n".join(lines) + "\nPONG: " + prompt[:200]

if "__FAIL__" in prompt:
    out("collecting tests ... running\nFAILED tests/test_calc.py::test_add - AssertionError\n")
    sys.stderr.write('Traceback (most recent call last):\n  File "app/calc.py", line 7, in add\n'
                     '    return a - b\nAssertionError: expected 3, got -1\n')
    sys.exit(3)
if "__HANG__" in prompt:
    signal.signal(signal.SIGTERM, signal.SIG_IGN)
    out("starting long job (partial log line)\n")
    child = subprocess.Popen(["sleep", "300"], preexec_fn=lambda: signal.signal(signal.SIGTERM, signal.SIG_IGN))
    with open(os.environ.get("FAKE_PIDFILE", os.devnull), "w") as fh:
        fh.write(str(os.getpid()) + "\n" + str(child.pid) + "\n")
    child.wait()
    sys.exit(0)
if "__PLAIN__" in prompt:
    out("plain text output, no json\n" + text + "\n")
    sys.exit(0)
if "__WRITE__:" in prompt:
    target = prompt.split("__WRITE__:", 1)[1].split()[0]
    with open(target, "w") as fh:
        fh.write("generated by fake harness\n")
    text += "\nwrote " + target
if "__EDIT__:" in prompt:
    target = prompt.split("__EDIT__:", 1)[1].split()[0]
    with open(target, "a") as fh:
        fh.write("appended by fake harness\n")
    text += "\nedited " + target

status_error = "__STATUSERR__" in prompt
if is_claude:
    payload = {
        "type": "result", "subtype": "error_during_execution" if status_error else "success",
        "is_error": status_error, "result": text, "session_id": "claude-sess-456", "num_turns": 2,
        "total_cost_usd": 0.0123,
        "usage": {"input_tokens": 2, "output_tokens": 7, "cache_read_input_tokens": 90, "cache_creation_input_tokens": 8},
        "modelUsage": {"fake-opus": {}},
        "permission_denials": [{"tool_name": "Bash"}] if "__DENIED__" in prompt else [],
        "terminal_reason": "completed",
    }
else:
    payload = {
        "conversation_id": "agy-conv-123", "status": "ERROR" if status_error else "SUCCESS", "response": text,
        "duration_seconds": 0.1, "num_turns": 2,
        "usage": {"input_tokens": 100, "output_tokens": 7, "total_tokens": 107},
    }
out(json.dumps(payload) + "\n")
'''


def _wait_dead(pids: list[int], timeout: float = 5.0) -> list[int]:
    """Poll until every pid is gone (or a zombie); return the survivors."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not any(bridge._pid_alive(p) for p in pids):
            return []
        time.sleep(0.1)
    return [p for p in pids if bridge._pid_alive(p)]


def result_text(result) -> str:
    return "\n".join(getattr(c, "text", "") for c in result.content if getattr(c, "type", "") == "text")


def input_schema(tool) -> dict:
    """mcp 2.x exposes Tool.input_schema, mcp 1.x Tool.inputSchema."""
    schema = getattr(tool, "input_schema", None)
    if schema is None:
        schema = getattr(tool, "inputSchema")
    return schema


CONFIG_KEYS = {"AGY_BIN", "AGY_AUTO_APPROVE_FLAGS", "AGY_DEFAULT_FLAGS", "CLAUDE_BIN", "CLAUDE_AUTO_APPROVE_FLAGS",
               "CLAUDE_DEFAULT_FLAGS", "CLAUDECODE"}


class BridgeTestCase(unittest.IsolatedAsyncioTestCase):
    """Shared fixture: temp dir with fake binaries, a work dir, and an env for the server."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="harness-bridge-test-"))
        self.fake_dir = self.tmp / "bin"
        self.fake_dir.mkdir()
        self.fake_agy = self._install_fake("agy")
        self.fake_claude = self._install_fake("claude")
        self.workdir = self.tmp / "project"
        self.workdir.mkdir()

    def _install_fake(self, name: str) -> Path:
        path = self.fake_dir / name
        path.write_text(FAKE_HARNESS)
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        return path

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def server_env(self, **overrides: str) -> dict[str, str]:
        env = {
            k: v
            for k, v in os.environ.items()
            if k not in CONFIG_KEYS and not k.startswith(("BRIDGE_", "FAKE_", "CLAUDE_CODE_"))
        }
        env.update(
            {
                "AGY_BIN": str(self.fake_agy),
                "CLAUDE_BIN": str(self.fake_claude),
                "BRIDGE_KILL_GRACE_SECONDS": "1",
                "BRIDGE_LOG_LEVEL": "WARNING",
            }
        )
        env.update(overrides)
        return env

    @contextlib.asynccontextmanager
    async def session(self, env: dict[str, str] | None = None, **overrides: str):
        params = StdioServerParameters(
            command=sys.executable, args=[str(SERVER)], env=env if env is not None else self.server_env(**overrides)
        )
        async with stdio_client(params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                yield session

    async def call(self, session: ClientSession, tool: str, **arguments) -> str:
        if tool.startswith("delegate_to_"):
            arguments.setdefault("working_dir", str(self.workdir))
        return result_text(await session.call_tool(tool, arguments))

    def init_repo(self) -> None:
        if not shutil.which("git"):
            self.skipTest("git not installed")
        subprocess.run(["git", "init", "-q"], cwd=self.workdir, check=True)


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestDiscovery(BridgeTestCase):
    async def test_tools_are_discoverable_with_expected_schema(self) -> None:
        async with self.session() as session:
            tools = {t.name: t for t in (await session.list_tools()).tools}
        self.assertEqual(
            set(tools),
            {"delegate_to_antigravity", "check_antigravity_health", "delegate_to_claude_code", "check_claude_code_health"},
        )
        for name in ("delegate_to_antigravity", "delegate_to_claude_code"):
            schema = input_schema(tools[name])
            props = schema["properties"]
            self.assertEqual(set(schema["required"]), {"prompt", "working_dir"})
            for prop in ("prompt", "working_dir", "flags", "auto_approve", "timeout_seconds", "conversation_id", "include_diff"):
                self.assertIn(prop, props, name)
            self.assertEqual(props["auto_approve"]["default"], True)
            self.assertEqual(props["timeout_seconds"]["default"], 900)
            self.assertEqual(props["include_diff"]["default"], False)
            self.assertIn("Conversation ID", tools[name].description)
        for name in ("check_antigravity_health", "check_claude_code_health"):
            self.assertFalse(input_schema(tools[name]).get("required"))
            self.assertIn("[HEALTH: READY]", tools[name].description)


# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestValidation(BridgeTestCase):
    async def test_missing_working_dir_is_rejected_before_execution(self) -> None:
        missing = self.tmp / "does-not-exist"
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="hello", working_dir=str(missing))
        self.assertTrue(text.startswith("[INVALID_ARGUMENT]"), text)
        self.assertIn("does not exist", text)
        self.assertIn(str(missing), text)
        self.assertNotIn("FAKE_ARGS", text)  # the harness was never launched

    async def test_file_instead_of_directory_is_rejected(self) -> None:
        file_path = self.tmp / "file.txt"
        file_path.write_text("x")
        async with self.session() as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="hello", working_dir=str(file_path))
        self.assertTrue(text.startswith("[INVALID_ARGUMENT]"), text)
        self.assertIn("not a directory", text)

    async def test_bad_prompt_timeout_flags_and_conversation_id(self) -> None:
        async with self.session() as session:
            empty = await self.call(session, "delegate_to_antigravity", prompt="   ")
            bad_timeout = await self.call(session, "delegate_to_antigravity", prompt="x", timeout_seconds=0)
            interactive = await self.call(session, "delegate_to_antigravity", prompt="x", flags=["-i"])
            double_print = await self.call(session, "delegate_to_claude_code", prompt="x", flags=["--print"])
            resume_flag = await self.call(session, "delegate_to_claude_code", prompt="x", flags=["--resume", "abc"])
            bad_conv = await self.call(session, "delegate_to_antigravity", prompt="x", conversation_id="--evil flag")
        for text in (empty, bad_timeout, interactive, double_print, resume_flag, bad_conv):
            self.assertTrue(text.startswith("[INVALID_ARGUMENT]"), text)
        self.assertIn("prompt", empty)
        self.assertIn("timeout_seconds", bad_timeout)
        self.assertIn("interactive", interactive)
        self.assertIn("prompt argument", double_print)
        self.assertIn("conversation_id", resume_flag)
        self.assertIn("conversation_id", bad_conv)


# ---------------------------------------------------------------------------
# Antigravity execution through the real MCP transport
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestAntigravityExecution(BridgeTestCase):
    async def test_success_report_parses_json_and_injects_flags(self) -> None:
        async with self.session(FAKE_ENV_MARKER="inherited-ok", CLAUDECODE="1") as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="say hello", flags=["--model", "fake-model-high"])
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("Harness: antigravity", text)
        self.assertIn("PONG: say hello", text)
        self.assertIn('Conversation ID: agy-conv-123  (pass conversation_id="agy-conv-123" to delegate_to_antigravity', text)
        self.assertIn("Harness stats: status=SUCCESS | turns=2 | tokens in/out=100/7", text)
        self.assertIn("--- harness response ---", text)
        args_line = next(ln for ln in text.splitlines() if ln.startswith("FAKE_ARGS:"))
        self.assertIn("--dangerously-skip-permissions", args_line)
        self.assertIn("--output-format json", args_line)
        self.assertIn("--print-timeout 960s", args_line)  # 900 + 60s margin
        self.assertIn("--model fake-model-high", args_line)
        self.assertIn("FAKE_PROMPT_SOURCE: arg", text)
        self.assertIn("FAKE_ENV_MARKER: inherited-ok", text)
        self.assertIn("FAKE_CLAUDECODE: 1", text)  # nothing is stripped for agy
        self.assertIn("FAKE_DEPTH: 1", text)  # child sees depth 0 + 1
        self.assertIn(f"FAKE_CWD: {self.workdir.resolve()}", text)
        self.assertIn("not a git repository", text)
        self.assertIn("<prompt: 9 chars>", text)  # the prompt is not echoed back in the Command line

    async def test_conversation_id_resumes_session(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="fix it", conversation_id="agy-conv-123")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("--conversation agy-conv-123", text)
        self.assertIn("FAKE_RESUME: agy-conv-123", text)

    async def test_auto_approve_false_and_user_overrides_are_respected(self) -> None:
        async with self.session() as session:
            text = await self.call(
                session,
                "delegate_to_antigravity",
                prompt="ping",
                auto_approve=False,
                flags=["--print-timeout", "10s", "--output-format", "text"],
            )
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        args_line = next(ln for ln in text.splitlines() if ln.startswith("FAKE_ARGS:"))
        self.assertNotIn("--dangerously-skip-permissions", args_line)
        self.assertIn("--print-timeout 10s", args_line)
        self.assertNotIn("960s", args_line)
        self.assertNotIn("--output-format json", args_line)
        self.assertIn("--output-format text", args_line)

    async def test_unstructured_output_falls_back_to_raw_text(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="__PLAIN__ hi")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("Conversation ID: (unavailable", text)
        self.assertIn("harness output (stdout, unstructured)", text)
        self.assertIn("plain text output, no json", text)

    async def test_harness_reported_error_with_exit_zero_is_a_roadblock(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="__STATUSERR__ do it")
        self.assertTrue(text.startswith("[ROADBLOCK / FAILURE]"), text)
        self.assertIn("reported failure (status=ERROR) despite exit 0", text)
        self.assertIn("Conversation ID: agy-conv-123", text)
        self.assertIn("ACTION REQUIRED", text)

    async def test_agy_discovered_via_path_when_agy_bin_unset(self) -> None:
        env = self.server_env()
        env.pop("AGY_BIN")
        env["PATH"] = f"{self.fake_dir}{os.pathsep}{env.get('PATH', '')}"
        async with self.session(env=env) as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="via path")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("PONG: via path", text)

    async def test_large_prompt_is_piped_via_stdin(self) -> None:
        big = "x" * (bridge.PROMPT_ARG_MAX_BYTES + 1000)
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt=big)
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("FAKE_PROMPT_SOURCE: stdin", text)
        self.assertIn(f"FAKE_PROMPT_LEN: {len(big)}", text)
        self.assertIn("piped via stdin", text)

    async def test_git_summary_and_full_diff(self) -> None:
        self.init_repo()
        tracked = self.workdir / "tracked.txt"
        tracked.write_text("original line\n")
        subprocess.run(["git", "add", "."], cwd=self.workdir, check=True)
        subprocess.run(
            ["git", "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "init"], cwd=self.workdir, check=True
        )
        async with self.session() as session:
            summary_only = await self.call(session, "delegate_to_antigravity", prompt="__WRITE__:newfile.txt")
            full = await self.call(
                session, "delegate_to_antigravity", prompt="__EDIT__:tracked.txt __WRITE__:other.txt", include_diff=True
            )
        self.assertTrue(summary_only.startswith("[SUCCESS]"), summary_only)
        self.assertIn("$ git status --short", summary_only)
        self.assertIn("?? newfile.txt", summary_only)
        self.assertIn("$ git diff --stat HEAD", summary_only)
        self.assertNotIn("$ git diff HEAD (plus untracked", summary_only)

        self.assertTrue(full.startswith("[SUCCESS]"), full)
        self.assertIn(" M tracked.txt", full)
        self.assertIn("$ git diff HEAD (plus untracked files via --no-index)", full)
        self.assertIn("+appended by fake harness", full)
        self.assertIn("+++ b/other.txt", full)
        self.assertIn("+generated by fake harness", full)

    async def test_failure_report_contains_diagnostics_and_call_to_action(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="run tests __FAIL__")
        self.assertTrue(text.startswith("[ROADBLOCK / FAILURE]"), text)
        self.assertIn("Exit code: 3", text)
        self.assertIn("Traceback (most recent call last):", text)
        self.assertIn("AssertionError: expected 3, got -1", text)
        self.assertIn("FAILED tests/test_calc.py::test_add", text)
        self.assertIn("detected diagnostics", text)
        self.assertIn("ACTION REQUIRED", text)
        self.assertIn("Probable cause: Task-level failure", text)

    async def test_timeout_kills_process_tree_and_returns_partial_logs(self) -> None:
        pidfile = self.tmp / "pids.txt"
        started = time.monotonic()
        async with self.session(FAKE_PIDFILE=str(pidfile)) as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="never finish __HANG__", timeout_seconds=2)
        elapsed = time.monotonic() - started
        self.assertTrue(text.startswith("[TIMEOUT_ERROR]"), text)
        self.assertIn("exceeded 2s", text)
        self.assertIn("starting long job (partial log line)", text)
        self.assertIn("partial stdout", text)
        self.assertLess(elapsed, 15, "timeout handling took too long (escalation to SIGKILL broken?)")
        pids = [int(p) for p in pidfile.read_text().split()]
        self.assertEqual(len(pids), 2, "fake harness should record its own pid and its child's pid")
        self.assertEqual(_wait_dead(pids), [], "harness process tree survived the timeout")

    async def test_missing_binary_is_reported_as_roadblock(self) -> None:
        async with self.session(AGY_BIN=str(self.tmp / "nope" / "agy")) as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="x")
        self.assertTrue(text.startswith("[ROADBLOCK / FAILURE]"), text)
        self.assertIn("not found", text)
        self.assertIn("check_antigravity_health", text)


# ---------------------------------------------------------------------------
# Claude Code execution through the real MCP transport
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestClaudeCodeExecution(BridgeTestCase):
    async def test_success_report_uses_claude_conventions_and_strips_session_env(self) -> None:
        async with self.session(CLAUDECODE="1", CLAUDE_CODE_SESSION_ID="parent-session") as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="say hello", flags=["--model", "fake-opus"])
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("Harness: claude_code", text)
        self.assertIn("PONG: say hello", text)
        self.assertIn('Conversation ID: claude-sess-456  (pass conversation_id="claude-sess-456" to delegate_to_claude_code', text)
        self.assertIn("status=success | turns=2 | tokens in/out=100/7 | cost=$0.0123 | model=fake-opus", text)
        args_line = next(ln for ln in text.splitlines() if ln.startswith("FAKE_ARGS:"))
        self.assertTrue(args_line.startswith("FAKE_ARGS: -p <PROMPT> "), args_line)  # boolean -p, positional prompt
        self.assertIn("--dangerously-skip-permissions", args_line)
        self.assertIn("--output-format json", args_line)
        self.assertNotIn("--print-timeout", args_line)  # claude has no print timeout flag
        self.assertIn("FAKE_CLAUDECODE: unset", text)  # parent session identity is hidden from the child
        self.assertIn("FAKE_DEPTH: 1", text)
        self.assertIn("Command: " + str(self.fake_claude) + " -p <prompt: 9 chars>", text)

    async def test_conversation_id_maps_to_resume_flag(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="fix it", conversation_id="claude-sess-456")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("--resume claude-sess-456", text)
        self.assertIn("FAKE_RESUME: claude-sess-456", text)

    async def test_leading_dash_prompt_goes_via_stdin(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="--not-a-flag: rename foo to bar")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("FAKE_PROMPT_SOURCE: stdin", text)
        self.assertIn("piped via stdin", text)
        args_line = next(ln for ln in text.splitlines() if ln.startswith("FAKE_ARGS:"))
        self.assertTrue(args_line.startswith("FAKE_ARGS: -p "), args_line)

    async def test_permission_denials_are_surfaced_as_a_note(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="__DENIED__ do it", auto_approve=False)
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("Note: 1 tool call(s) were denied by permissions", text)

    async def test_is_error_result_is_a_roadblock(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="__STATUSERR__ do it")
        self.assertTrue(text.startswith("[ROADBLOCK / FAILURE]"), text)
        self.assertIn("reported failure (status=error_during_execution) despite exit 0", text)

    async def test_timeout_kills_claude_process_tree(self) -> None:
        pidfile = self.tmp / "pids.txt"
        async with self.session(FAKE_PIDFILE=str(pidfile)) as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="never finish __HANG__", timeout_seconds=2)
        self.assertTrue(text.startswith("[TIMEOUT_ERROR]"), text)
        pids = [int(p) for p in pidfile.read_text().split()]
        self.assertEqual(_wait_dead(pids), [], "harness process tree survived the timeout")


# ---------------------------------------------------------------------------
# Depth guard
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestDepthGuard(BridgeTestCase):
    async def test_delegation_is_refused_at_max_depth(self) -> None:
        async with self.session(BRIDGE_DEPTH="1") as session:
            text = await self.call(session, "delegate_to_claude_code", prompt="recurse")
            health = await self.call(session, "check_claude_code_health")
        self.assertTrue(text.startswith("[ROADBLOCK / FAILURE]"), text)
        self.assertIn("nesting depth 1 has reached BRIDGE_MAX_DEPTH=1", text)
        self.assertNotIn("FAKE_ARGS", text)
        self.assertIn("Delegation depth: 1 of max 1", health)

    async def test_raised_max_depth_allows_and_increments(self) -> None:
        async with self.session(BRIDGE_DEPTH="1", BRIDGE_MAX_DEPTH="2") as session:
            text = await self.call(session, "delegate_to_antigravity", prompt="recurse once")
        self.assertTrue(text.startswith("[SUCCESS]"), text)
        self.assertIn("FAKE_DEPTH: 2", text)


# ---------------------------------------------------------------------------
# Health checks
# ---------------------------------------------------------------------------


@unittest.skipUnless(os.name == "posix", "fake harnesses need a POSIX shell environment")
class TestHealth(BridgeTestCase):
    async def test_antigravity_ready(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "check_antigravity_health")
        self.assertTrue(text.startswith("[HEALTH: READY]"), text)
        self.assertIn("Version: 9.9.9-fake", text)
        self.assertIn("authenticated (2 models", text)
        self.assertIn("fake-model-high", text)
        self.assertIn(str(self.fake_agy), text)

    async def test_claude_code_ready_without_leaking_account_details(self) -> None:
        async with self.session() as session:
            text = await self.call(session, "check_claude_code_health")
        self.assertTrue(text.startswith("[HEALTH: READY]"), text)
        self.assertIn("Version: 9.9.9-fake (Claude Code)", text)
        self.assertIn("authenticated (method=claude.ai, subscription=max, provider=firstParty)", text)
        self.assertNotIn("secret-email", text)
        self.assertNotIn("secret-org", text)
        self.assertIn("Env hidden from the harness: CLAUDECODE, CLAUDE_CODE_SESSION_ID", text)

    async def test_degraded_when_unauthenticated(self) -> None:
        async with self.session(FAKE_AUTH_FAIL="1") as session:
            agy = await self.call(session, "check_antigravity_health")
            claude = await self.call(session, "check_claude_code_health")
        self.assertTrue(agy.startswith("[HEALTH: DEGRADED]"), agy)
        self.assertIn("NOT authenticated", agy)
        self.assertIn("not authenticated. Run 'agy'", agy)
        self.assertTrue(claude.startswith("[HEALTH: DEGRADED]"), claude)
        self.assertIn("loggedIn=false", claude)

    async def test_unavailable_when_binary_missing(self) -> None:
        async with self.session(AGY_BIN="definitely-not-a-real-binary-xyz", CLAUDE_BIN="/nope/claude") as session:
            agy = await self.call(session, "check_antigravity_health")
            claude = await self.call(session, "check_claude_code_health")
        for text, var in ((agy, "AGY_BIN"), (claude, "CLAUDE_BIN")):
            self.assertTrue(text.startswith("[HEALTH: UNAVAILABLE]"), text)
            self.assertIn("not found", text)
            self.assertIn(var, text)


# ---------------------------------------------------------------------------
# Direct unit tests of the pure helpers and the process runner
# ---------------------------------------------------------------------------


class TestHelpers(unittest.TestCase):
    def test_build_argv_antigravity_defaults(self) -> None:
        argv, stdin = bridge.build_argv(AGY, "/bin/agy", "do it", [], True, 900, approve_flags=["--dangerously-skip-permissions"], extra_flags=[])
        self.assertIsNone(stdin)
        self.assertEqual(argv[:3], ["/bin/agy", "-p", "do it"])
        self.assertIn("--dangerously-skip-permissions", argv)
        self.assertEqual(argv[argv.index("--output-format") + 1], "json")
        self.assertEqual(argv[argv.index("--print-timeout") + 1], "960s")

    def test_build_argv_claude_defaults_and_resume(self) -> None:
        argv, stdin = bridge.build_argv(CLAUDE, "/bin/claude", "do it", ["--max-turns", "5"], True, 60, "sess-1", approve_flags=["--dangerously-skip-permissions"], extra_flags=["--model", "m"])
        self.assertIsNone(stdin)
        self.assertEqual(argv[:5], ["/bin/claude", "-p", "do it", "--resume", "sess-1"])
        self.assertNotIn("--print-timeout", argv)
        self.assertEqual(argv[-4:], ["--model", "m", "--max-turns", "5"])

    def test_build_argv_no_auto_approve_and_no_duplicate_injection(self) -> None:
        argv, _ = bridge.build_argv(AGY, "agy", "p", ["--print-timeout=5s", "--mode", "plan"], False, 30, approve_flags=["--mode", "always-proceed"], extra_flags=[])
        self.assertNotIn("always-proceed", argv)
        self.assertEqual(argv.count("--print-timeout=5s"), 1)
        self.assertNotIn("--print-timeout", argv)
        argv2, _ = bridge.build_argv(AGY, "agy", "p", ["--mode", "plan"], True, 30, approve_flags=["--mode", "always-proceed"], extra_flags=[])
        self.assertNotIn("always-proceed", argv2, "user-supplied --mode must not be overridden by the auto-approve group")

    def test_build_argv_stdin_fallbacks(self) -> None:
        big = "y" * (bridge.PROMPT_ARG_MAX_BYTES + 1)
        argv, stdin = bridge.build_argv(AGY, "agy", big, ["--sandbox"], True, 10, approve_flags=["--x"], extra_flags=[])
        self.assertEqual(stdin, big.encode())
        self.assertNotIn("-p", argv)
        argv, stdin = bridge.build_argv(CLAUDE, "claude", "-starts with dash", [], True, 10, approve_flags=[], extra_flags=[])
        self.assertEqual(stdin, b"-starts with dash")
        self.assertEqual(argv[:2], ["claude", "-p"])
        self.assertNotIn("-starts with dash", argv)

    def test_build_argv_rejects_interactive_prompt_and_resume_flags(self) -> None:
        for harness, bad in ((AGY, ["-i"]), (AGY, ["--prompt-interactive=x"]), (AGY, ["-p"]), (CLAUDE, ["--print"]), (CLAUDE, ["--resume", "x"]), (AGY, ["--conversation=x"])):
            with self.assertRaises(ValueError, msg=f"{harness.key} {bad}"):
                bridge.build_argv(harness, "bin", "p", bad, True, 10, approve_flags=[], extra_flags=[])

    def test_child_env_strips_session_identity_and_sets_depth(self) -> None:
        saved = {k: os.environ.get(k) for k in ("CLAUDECODE", "CLAUDE_CODE_SESSION_ID", "CLAUDE_CODE_USE_BEDROCK", "BRIDGE_DEPTH", "BRIDGE_STRIP_ENV", "SECRET_X")}
        try:
            os.environ.update({"CLAUDECODE": "1", "CLAUDE_CODE_SESSION_ID": "s", "CLAUDE_CODE_USE_BEDROCK": "1", "BRIDGE_DEPTH": "3", "BRIDGE_STRIP_ENV": "SECRET_X", "SECRET_X": "v"})
            env = CLAUDE.child_env()
            self.assertNotIn("CLAUDECODE", env)
            self.assertNotIn("CLAUDE_CODE_SESSION_ID", env)
            self.assertEqual(env["CLAUDE_CODE_USE_BEDROCK"], "1")  # settings are kept
            self.assertNotIn("SECRET_X", env)
            self.assertEqual(env["BRIDGE_DEPTH"], "4")
            self.assertEqual(env["PATH"], os.environ["PATH"])
            self.assertIn("CLAUDECODE", AGY.child_env())
        finally:
            for k, v in saved.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

    def test_parse_outcome_shapes(self) -> None:
        agy = bridge.parse_outcome(AGY, 'Fetching...\n{"conversation_id": "c1", "status": "SUCCESS", "response": "DONE", "num_turns": 3, "usage": {"input_tokens": 10, "output_tokens": 2}}')
        self.assertEqual((agy.conversation_id, agy.text, agy.harness_error, agy.turns, agy.tokens_in), ("c1", "DONE", False, 3, 10))
        claude = bridge.parse_outcome(CLAUDE, '{"type": "result", "subtype": "error_max_turns", "is_error": true, "result": "stuck", "session_id": "s1", "num_turns": 9, "total_cost_usd": 1.5, "usage": {"input_tokens": 1, "cache_read_input_tokens": 2, "output_tokens": 3}, "modelUsage": {"claude-x": {}}, "permission_denials": [{}, {}]}')
        self.assertEqual((claude.conversation_id, claude.text, claude.harness_error, claude.status, claude.tokens_in, claude.cost_usd, claude.model), ("s1", "stuck", True, "error_max_turns", 3, 1.5, "claude-x"))
        self.assertTrue(any("denied" in n for n in claude.notes))
        raw = bridge.parse_outcome(AGY, "just text")
        self.assertEqual((raw.structured, raw.text, raw.conversation_id), (False, "just text", None))
        self.assertIsNone(bridge._extract_json_object("not { json"))

    def test_validate_working_dir(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path, err = bridge.validate_working_dir(tmp)
            self.assertIsNone(err)
            self.assertEqual(path, Path(tmp).resolve())
            _, err = bridge.validate_working_dir(str(Path(tmp) / "missing"))
            self.assertIn("does not exist", err)
            _, err = bridge.validate_working_dir("")
            self.assertIn("non-empty", err)
            _, err = bridge.validate_working_dir(None)  # type: ignore[arg-type]
            self.assertIn("non-empty", err)

    def test_truncate_keeps_head_and_tail(self) -> None:
        text = "A" * 500 + "B" * 500
        out = bridge.truncate(text, 200)
        self.assertLess(len(out), 320)
        self.assertTrue(out.startswith("A" * 50))
        self.assertTrue(out.endswith("B" * 50))
        self.assertIn("truncated", out)
        self.assertEqual(bridge.truncate("short", 200), "short")

    def test_clean_text_strips_ansi(self) -> None:
        self.assertEqual(bridge.clean_text("\x1b[31mred\x1b[0m\r\nnext\rline"), "red\nnext\nline")

    def test_extract_diagnostics_captures_traceback_block(self) -> None:
        raw = "\n".join(
            [
                "collecting ...", "line 2", "line 3",
                "Traceback (most recent call last):", '  File "x.py", line 1, in <module>', "    boom()",
                "ZeroDivisionError: division by zero",
                "unrelated 1", "unrelated 2", "unrelated 3", "unrelated 4", "unrelated 5", "unrelated 6",
                "FAILED tests/test_x.py::test_y", "end",
            ]
        )
        diag = bridge.extract_diagnostics(raw)
        self.assertIn("Traceback (most recent call last):", diag)
        self.assertIn("ZeroDivisionError: division by zero", diag)
        self.assertIn("FAILED tests/test_x.py::test_y", diag)
        self.assertNotIn("unrelated 2", diag)  # gap between the traceback block and the FAILED line
        self.assertIn("unrelated 6", diag)  # context line before FAILED
        self.assertIn("    ...", diag)
        self.assertEqual(bridge.extract_diagnostics("all good\nnothing to see"), "")

    def test_classify_failure(self) -> None:
        self.assertIn("quota", bridge.classify_failure(AGY, 1, "", "HTTP 429 too many requests"))
        self.assertIn("Authentication", bridge.classify_failure(CLAUDE, 1, "", "unauthenticated"))
        self.assertIn("CLI usage", bridge.classify_failure(AGY, 2, "", 'Error: unexpected argument "auth"'))
        self.assertIn("CLI usage", bridge.classify_failure(CLAUDE, 1, "", "error: unknown option '--bogus'"))
        self.assertIn("Task-level", bridge.classify_failure(AGY, 1, "FAILED x", ""))
        self.assertIn("signal", bridge.classify_failure(AGY, -9, "", ""))

    def test_bounded_buffer_keeps_head_and_tail(self) -> None:
        buf = bridge._BoundedBuffer(10)
        buf.write(b"0123456789")
        buf.write(b"abcdefghij")
        buf.write(b"KLMNOPQRST")
        text = buf.text()
        self.assertTrue(text.startswith("0123456789"))
        self.assertTrue(text.endswith("KLMNOPQRST"))
        self.assertIn("10 bytes dropped", text)


@unittest.skipUnless(os.name == "posix", "uses bash")
class TestProcessRunner(unittest.IsolatedAsyncioTestCase):
    async def test_cancellation_kills_process_tree(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            pidfile = Path(tmp) / "pids"
            script = (
                "trap '' TERM; ( trap '' TERM; exec sleep 300 ) & c=$!; "
                f"printf '%s\\n%s\\n' $$ $c > {pidfile}; wait $c"
            )
            task = asyncio.ensure_future(bridge.run_process(["bash", "-c", script], cwd=tmp, timeout=60, kill_grace=1))
            for _ in range(50):
                await asyncio.sleep(0.1)
                if pidfile.exists() and len(pidfile.read_text().split()) == 2:
                    break
            pids = [int(p) for p in pidfile.read_text().split()]
            task.cancel()
            with self.assertRaises(asyncio.CancelledError):
                await task
            self.assertEqual(_wait_dead(pids), [], "process tree survived task cancellation")

    async def test_timeout_returns_partial_output_and_kills_tree(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            pidfile = Path(tmp) / "pids"
            script = (
                "echo partial-out; echo partial-err >&2; trap '' TERM; ( trap '' TERM; exec sleep 300 ) & c=$!; "
                f"printf '%s\\n%s\\n' $$ $c > {pidfile}; wait $c"
            )
            result = await bridge.run_process(["bash", "-c", script], cwd=tmp, timeout=1, kill_grace=1)
            self.assertTrue(result.timed_out)
            self.assertIsNone(result.returncode)
            self.assertIn("partial-out", result.stdout)
            self.assertIn("partial-err", result.stderr)
            pids = [int(p) for p in pidfile.read_text().split()]
            self.assertEqual(_wait_dead(pids), [], "process tree survived the timeout")

    async def test_normal_exit_codes_are_reported(self) -> None:
        ok = await bridge.run_process(["bash", "-c", "echo hi; exit 0"], cwd="/", timeout=10, kill_grace=1)
        self.assertEqual((ok.returncode, ok.stdout.strip(), ok.timed_out), (0, "hi", False))
        bad = await bridge.run_process(["bash", "-c", "echo oops >&2; exit 7"], cwd="/", timeout=10, kill_grace=1)
        self.assertEqual((bad.returncode, bad.stderr.strip()), (7, "oops"))
        fed = await bridge.run_process(["cat"], cwd="/", timeout=10, stdin_data=b"from-stdin", kill_grace=1)
        self.assertEqual(fed.stdout, "from-stdin")


if __name__ == "__main__":
    unittest.main(verbosity=2)
